package.json, pino-elasticsearch.js, test/acceptance.test.js, test/unit.test.js
When using hapi-pino with `prettyPrint: true` the module will complain that the value.time doesn't exist.
The pr won't fixes the issue but at least the logger is not going to explode.
I might fix in another pr but the issue is when parsing the JSON so we might want to pass a flag that says `Hi that's a pretty JSON` :)
Currently, I'm by passing that by using `prettyPrint: false`
=> Making sure the logger not breaking.

pino-elasticsearch.js
elasticsearch looking for httpAuth, not auth key
- [config options for elasticsearch.Client](https://github.com/elastic/elasticsearch-js/blob/8cf09a381db61478082d8f964e5fe5ac96bb7c5e/docs/configuration.asciidoc#config-options)
- https://github.com/elastic/elasticsearch-js/blob/master/src/lib/host.js#L104
=== debug
`curl -i elastic:changeme elastic.example.com` works
running `nodemon -w ./app --inspect=0.0.0.0:9229 | pino-elasticsearch -H elastic.example.com -p 80 --user elastic --password changeme -l trace`
```
Elasticsearch TRACE: 2017-10-15T21:39:34Z
-> POST http://elastic.example.com:80/_bulk
{...}
<- 401
{
"error": {
"root_cause": [
{
"type": "security_exception",
"reason": "missing authentication token for REST request [/_bulk]",
"header": {
"WWW-Authenticate": "Basic …
```
=> Fix basic auth for elasticsearch module

README.md, pino-elasticsearch.js, test/acceptance.test.js, usage.txt
Logstash default option for ElasticSearch is to include the date in the index: https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-index
This is quite useful for housekeeping in general, and I'd love to see a similar feature here, I made a quick amendment to support something similar to start a discussion about that, please let me know what you think
=> Allow for Date in index

pino-elasticsearch.js, test/acceptance.test.js
Following-up with https://github.com/pinojs/pino-elasticsearch/issues/27
=> Ignore lines containing a JSON-parseable boolean

.travis.yml, README.md, package.json, pino-elasticsearch.js, test/acceptance.test.js, test/unit.test.js, usage.txt
As titled.
This pr also removes the aws configuration, since the package has not been updated to support the new client.
It introduces two new cli options:
- `node`: the URL where Elasticsearch is running
- `es-version`: the major version of Elasticsearch you are using (needed only if ≤7)
It removes `host`, `port`, `aws-credentials`.
The minimum version of Node.js required is v8.
=> Use the new Elasticsearch client

README.md
I found useful to add this snippet, so users may use this package not only via CLI
=> add "usage as module" section

cli.js, lib.js, package.json
Importing this library into a project with a bundler (webpack) needs to use shebang-loader. Also, Isolating library code improves readability.
=> Split cli and lib files

README.md, lib.js, usage.txt
The `pino-to-ecs` will be deprecated in favor of [`@elastic/ecs-pino-format`](https://github.com/elastic/ecs-logging-js/tree/master/loggers/pino), this pr adds a warning if the `ecs` option is used.
The documentation has been updated to explain how to use the new module.
=> Log a warning if ecs option is used

README.md, cli.js, lib.js, package.json, test/acceptance.test.js, test/unit.test.js, usage.txt
The latest version of the client offers a bulk indexer, which automatically handles the retries and lets you pick the flush bytes threshold.
You can find the bulk indexer documentation [here](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-helpers.html).
The mechanics are slightly different, you can only know if a document has failed, so the `insert` event, which as far as I know it is only used for testing, will not be emitted more than once.
The test now will fail because I didn't update the monkey patch yet, but I wanted to have an early feedback before continuing, especially around the stream handling.
This pr makes useless the `bulk-size` option, as the client's bulk indexer needs a value in bytes. This because you can't know in advance the size of …
=> Use the client bulk indexer

README.md, cli.js, lib.js, test/unit.test.js, usage.txt
closes #57 
* `30000` as a default option, same as in the client.
* `t` is the new flag for the CLI.
=> `flush-interval` setting added

README.md, cli.js, lib.js, usage.txt
Kibana and ElasticSearch require https to be set up, even for private networks, but all connections got rejected.
=> Don't reject private network https connections

README.md, lib.js
Allow custom Connection object for the ElasticSearch Client.
Reason: Some providers such as AWS need requests to be signed using custom logic. The client allows a custom Connection to handle these things. This keeps  the logic from being needed inside of the pino-elasticsearch package itself, as there are many Connection packages/custom solutions already in use, ready to plug into it.
Example usage:
```
const Conenction = <my custom ES Connection class>
const streamToElastic = pinoElastic({
index: 'test-index',
consistency: 'one',
node: process.env.ELASTICSEARCH_URL,
'es-version': 7,
'flush-bytes': 1000,
Connection
})
```
Behavior when not included is to use the default one from the ElasticSearch Client.
Example script using modified version: …
=> [feature] Custom Connection Support for ES Client

README.md, cli.js, usage.txt
enable CLI to read config file
Usage:
`node ./index.js | tee -a ./pino_log/http.log | jq -c 'del(.req.headers) | del(.http.response.headers) | del(.redact)' | pino-elasticsearch -r config.json`
=> feat: enable to read config file

README.md, docker-compose-v7-es-only-datastreams.yml, lib.js, test/acceptance.test.js, test/unit.test.js
This PR allows users to specify the datastream name as the index and set the op_type to create.
AFAIK this doesn't break any existing functionality.
=> Datastream support using op_type create config

.github/workflows/ci.yml
BREAKING CHANGE: Drops support for EOL node 10 and 12; adds support for node 18
=> chore!: drop support for node 10 and 12; add support for node 18

.github/workflows/ci.yml, README.md, docker-compose-v8.yml, lib.js, package.json, test/acceptance.test.js
=> build(deps): bump @elastic/elasticsearch from 7.7.1 to 8.2.1

package.json
Not used in scripts or source anywhere.
=> build(deps): remove unused readable-stream

README.md, cli.js, example.js, lib.d.ts, lib.js, package.json, test-d/lib.test-d.ts, test/acceptance.test.js, test/unit.test.js, usage.txt
opened the PR in here by mistake (meant to merge it in my fork's `master` branch) so feel free to close it
but this PR does fix https://github.com/pinojs/pino-elasticsearch/issues/166 and it also adds types so it's easier to use this library in a typescript project
=> fix support for elasticsearch v7 + add types

cli.js, test/cli.test.js, test/exampleConfig.js
the options passed to the client does not include ```rejectUnauthorized``` because the value is added after the client is create.
So, I moved the code right before the client creation.
the check for allowed keys will skip the key if the value is false, so the options will not include the key. To fix this, the code should only skip if the value is undefined. 
```
allowedProps.forEach(key => {
if (config[key] !== undefined) { flags[key] = config[key] }
})
```
=> fix bug: opts.rejectUnauthorized for SSL option

lib.js, test/unit.test.js
#180 In version 8 renamed the ssl option to tls. 
This commit adjusts the code to reflect this change, ensuring compatibility with Elasticsearch 8.
[Rename ssl option to tls](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html#_rename_ssl_option_to_tls)
[Link to documentation](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-connecting.html#auth-tls)
=> fix(elastic): rename ssl options to tls

package.json
This PR addresses this issue https://github.com/pinojs/pino-elasticsearch/issues/186 for updating ping to v9
=> Updated dependencies to the latest version
