pinojs/pino-elasticsearch

.travis.yml
docker-compose-v2.yml
docker-compose-v5.yml
jdk_switcher.sh
package.json
pino-elasticsearch.js
test.js

cc @dadoonet @sitkb @megastef please review.

Suppor for elastic v5.

---

README.md
package.json
pino-elasticsearch-aws.js
pino-elasticsearch.js
usage.txt

Hi! This is my first pull request. Not sure if I am doing right.

Add support for AWS Elasticsearch

---

pino-elasticsearch.js
test/fixtures.js
test/unit.test.js

**Description**
Check for consistency in the value object before proceeding to create date object.
**Reference**
This is a proposal PR for #19

ISSUE-19 Check value before setting date object

---

.travis.yml

Sleep before run test

---

docker-compose-v7.yml

Added docker-compose for ES7

---

README.md
package.json
pino-elasticsearch.js
test/acceptance.test.js
test/unit.test.js
usage.txt

As titled:
For reference: https://www.elastic.co/guide/en/ecs/current/ecs-reference.html

 Added ecs format support

---

.github/workflows/ci.yml
package.json
test/acceptance.test.js
test/unit.test.js

Use is-elasticsearch-running to have more reliable test

---

README.md
cli.js
lib.js
test/unit.test.js
usage.txt

Adding support for additional authentication options in client

---

README.md

README: fix `docker-compose up` command

---

README.md

I encountered these issues when integrating the library locally and decided to document them.  I noticed some of the other PRs add similar documentation.  If you don't want to deconflict this, please don't hesitate to close this PR -- I understand that you are busy.

Update README to document steps to troubleshoot common issues.

---

lib.js

Ref https://github.com/pinojs/pino/pull/1003

Add _destroy to support multithread transport

---

README.md
cli.js

This will reduce debug time, related issue: #53

Clearify error handling and print error in cli mode

---

cli.js

Hi,
Please have a look at the change, currently the wrong stream is used so no errors are shown.
I also added a json error output.
Let me know what you think.
It would also be nice to have a command line option to forward the input to stdout without a script or code around it.

Fix usage of steam, added logging of json errors

---

.github/workflows/ci.yml

ci: bump github actions

---

package.json

chore(package): remove engines field

---

lib.js
test/unit.test.js

This resurrects elastic connection pool in case elastic server is down or the connection is broken for some reason.

Elastic connection resurrect on split destroy

---

example.js
lib.js
test/unit.test.js

fix reconnection #72
fix flood of resurrect

fix reconnection

---

lib.d.ts
lib.js
package.json
test/acceptance.test.js
test/unit.test.js

Added support for version 8 of elastic client

Support elastic client 8

---

README.md

Replace pino-multi-stream with pino.transport in Readme.md

---

README.md

fix: ecs package incorrect url
